packages:
  - packages/*
  - examples/*
  - tools/dbpatch
  - website/

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - esbuild
  - nx
  - sharp
  - tree-sitter
  - tree-sitter-haskell
